### ISSUE TITLE
Error for empty grids

### ISSUE THREAD

**Issue by lfehrma** [AWF-GAUG/gsgsim#2]
When a GSG is generated that has no points in the selected boundary, we get an error from the gen_gsg function. Probably it comes from trying to subset the empty dataframe coords. If we excecute the function via shiny, the app just stopps. Soemhow we need to ensure that a SpatialPointsDataFrame is written (even if it is empty empty).

**Comment by sebschnell** [comment]
Done. When there are no points in the boundary, the function stops and throws an error with the recommendation of adjusting the distance. Hope shiny can handle this.

**Comment by ckukunda** [comment]
We still have the same problem in shiny! We think the problem is in 
 coord <- cbind(as.vector(t(lon_mat)), lat);
  colnames(coord) <- c("X", "Y");
or one step later where the boundary is used to subset. Try Aruba with 250 km in shiny!

**Comment by sebschnell** [comment]
I know, I know, I'm working on it. I just need to find out how to place a warning. Patience please :)

**Comment by sebschnell** [comment]
gen_gsg is now returning a SpatialPoints (sp) object with only one coordinate (0, 0). In addition a warning is written to the R-console. I could, however, not find out how to place the same warning in shiny - it is not visible there. For now it should be fine because we know it. For a more user friendly behavior I need more time. Or someone else has an idea. There is a validate function in shiny but I think some rebuilding of server.R is needed to make it work. As  said, I would need more time to fix it.
